import {Pencil,Trash2} from 'lucide-react';
import {syncNow} from '../sync/engine';
import {useEffect,useState} from 'react';
import type {Account} from '../sync/model';
import {accountRequest} from '../sync/transport';
type Book={id:string;title:string;author:string;series:string;volume:number|null;uploaded:boolean;watched:boolean};
export function LibraryBooks({account,library,onChange}:{account:Account;library:string;onChange():Promise<void>}){
 const [query,setQuery]=useState(''),[books,setBooks]=useState<Book[]>([]),[open,setOpen]=useState(false),[editing,setEditing]=useState<Book>(),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function refresh(){setBooks(await accountRequest(account,`/v1/admin/libraries/${library}/books`));}
 useEffect(()=>{if(!open)return;const update=()=>{void refresh().catch(e=>setError(e.message));};window.addEventListener('quire-synced',update);return()=>window.removeEventListener('quire-synced',update);},[open,library]);
 async function run(action:()=>Promise<unknown>){setBusy(true);setError('');try{await action();await refresh();await onChange();await syncNow();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 return <div><button disabled={busy} onClick={()=>{setOpen(!open);if(!open)void run(refresh);}}>{open?'Hide books':'Manage books'}</button>{error&&<p role="alert">{error}</p>}{open&&<div><label className="admin-search">Find a book<input type="search" placeholder="Search title or author" value={query} onChange={e=>setQuery(e.target.value)}/></label>{books.filter(b=>(b.title+' '+b.author).toLowerCase().includes(query.toLowerCase())).map(b=><div className="admin-book" key={b.id}>{editing?.id===b.id?<form onSubmit={e=>{e.preventDefault();void run(async()=>{const {title,author,series,volume}=editing;await accountRequest(account,`/v1/admin/libraries/${library}/books/${b.id}/metadata`,{title,author,series,volume},'PUT');setEditing(undefined);});}}><label>Title<input required maxLength={1000} value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label>Author<input maxLength={500} value={editing.author} onChange={e=>setEditing({...editing,author:e.target.value})}/></label><label>Series<input maxLength={500} value={editing.series} onChange={e=>setEditing({...editing,series:e.target.value})}/></label><label>Volume<input type="number" min={0} value={editing.volume??''} onChange={e=>setEditing({...editing,volume:e.target.value===''?null:Number(e.target.value)})}/></label><button className="primary" disabled={busy}>Save metadata</button><button type="button" onClick={()=>setEditing(undefined)}>Cancel</button></form>:<><strong>{b.title||'Untitled'}</strong><p className="muted">{b.author} · {b.watched?(b.uploaded?'Uploaded and watched':'Watched folder'):'Uploaded'}</p><div className="admin-actions"><button onClick={()=>setEditing(b)}><Pencil/> Edit metadata</button>{b.uploaded&&<button disabled={busy} onClick={()=>{if(window.confirm(b.watched?'Delete the uploaded file? The watched copy remains available. Original files and reading data stay intact.':'Delete this uploaded server file? Members will keep downloaded copies and reading data, but cannot download it again from this library.'))void run(()=>accountRequest(account,`/v1/admin/libraries/${library}/books/${b.id}`,undefined,'DELETE'));}}><Trash2/> Delete uploaded file</button>}</div>{b.watched&&<p className="muted">Watched originals are read-only. Use Watched folders to stop sharing the folder.</p>}</>}</div>)}{books.length>0&&!books.some(b=>(b.title+' '+b.author).toLowerCase().includes(query.toLowerCase()))&&<p className="muted">No matching books.</p>}{books.length===0&&<p className="muted">No books yet. Upload an EPUB or add a watched folder.</p>}</div>}</div>;
}
