import {useState} from 'react';
import type {Account} from '../sync/model';
import {accountRequest} from '../sync/transport';
type Book={id:string;title:string;author:string;series:string;volume:number|null;uploaded:boolean;watched:boolean};
export function LibraryBooks({account,library}:{account:Account;library:string}){
 const [books,setBooks]=useState<Book[]>([]),[open,setOpen]=useState(false),[editing,setEditing]=useState<Book>(),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function refresh(){setBooks(await accountRequest(account,`/v1/admin/libraries/${library}/books`));}
 async function run(action:()=>Promise<unknown>){setBusy(true);setError('');try{await action();await refresh();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 return <div><button disabled={busy} onClick={()=>{setOpen(!open);if(!open)void run(refresh);}}>{open?'Hide books':'Manage books'}</button>{error&&<p role="alert">{error}</p>}{open&&<div>{books.map(b=><div className="admin-book" key={b.id}>{editing?.id===b.id?<form onSubmit={e=>{e.preventDefault();void run(async()=>{const {title,author,series,volume}=editing;await accountRequest(account,`/v1/admin/libraries/${library}/books/${b.id}/metadata`,{title,author,series,volume},'PUT');setEditing(undefined);});}}><label>Title<input required maxLength={1000} value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label>Author<input maxLength={500} value={editing.author} onChange={e=>setEditing({...editing,author:e.target.value})}/></label><label>Series<input maxLength={500} value={editing.series} onChange={e=>setEditing({...editing,series:e.target.value})}/></label><label>Volume<input type="number" min={0} value={editing.volume??''} onChange={e=>setEditing({...editing,volume:e.target.value===''?null:Number(e.target.value)})}/></label><button className="primary" disabled={busy}>Save metadata</button><button type="button" onClick={()=>setEditing(undefined)}>Cancel</button></form>:<><strong>{b.title||'Untitled'}</strong><p className="muted">{b.author} · {b.watched?'Watched folder':'Uploaded'}</p><button onClick={()=>setEditing(b)}>Edit metadata</button>{b.uploaded&&<button disabled={busy} onClick={()=>{if(window.confirm('Remove this uploaded server copy? Downloaded copies and reading data will remain.'))void run(()=>accountRequest(account,`/v1/admin/libraries/${library}/books/${b.id}`,undefined,'DELETE'));}}>Remove upload</button>}</>}</div>)}{books.length===0&&<p className="muted">No books yet. Upload an EPUB or add a watched folder.</p>}</div>}</div>;
}
