use std::collections::{BTreeMap, BTreeSet};
use tauri::utils::{
    acl::{capability::Capability, manifest::Manifest, resolved::Resolved, ExecutionContext},
    platform::Target,
};

#[test]
fn registered_commands_are_allowed_only_in_the_local_main_window() {
    // Use the manifest generated by Tauri's build, not a mocked invoke handler.
    let manifests: BTreeMap<String, Manifest> = serde_json::from_str(include_str!(concat!(
        env!("OUT_DIR"),
        "/acl-manifests.json"
    )))
    .unwrap();
    let main: Capability = serde_json::from_str(include_str!("../capabilities/main.json")).unwrap();
    let handlers = include_str!("lib.rs")
        .split("tauri::generate_handler![")
        .nth(1)
        .unwrap()
        .split(']')
        .next()
        .unwrap();
    let registered: BTreeSet<_> = handlers
        .split(',')
        .filter_map(|path| path.trim().rsplit("::").next())
        .filter(|name| !name.is_empty())
        .map(str::to_owned)
        .collect();
    assert!(registered.contains("desktop_open_pending"));
    assert!(registered.contains("screen_capture"));

    for target in [
        Target::Windows,
        Target::MacOS,
        Target::Linux,
        Target::Android,
        Target::Ios,
    ] {
        let resolved = Resolved::resolve(
            &manifests,
            BTreeMap::from([(main.identifier.clone(), main.clone())]),
            target,
        )
        .unwrap();
        assert!(resolved.has_app_acl);
        let allowed: BTreeSet<_> = resolved
            .allowed_commands
            .keys()
            .filter(|command| !command.starts_with("plugin:"))
            .cloned()
            .collect();
        assert_eq!(
            allowed, registered,
            "Application command permissions on {target}"
        );
        for command in &registered {
            assert!(!resolved.denied_commands.contains_key(command));
            let grants = &resolved.allowed_commands[command];
            assert!(!grants.is_empty());
            for grant in grants {
                assert!(matches!(grant.context, ExecutionContext::Local));
                assert_eq!(
                    grant
                        .windows
                        .iter()
                        .map(|pattern| pattern.as_str())
                        .collect::<Vec<_>>(),
                    ["main"]
                );
                assert!(grant.webviews.is_empty());
            }
        }
    }
}
